"""Add quality to events

Revision ID: b2dd455acfd4
Revises: c9fd7c7de7c0
Create Date: 2025-07-06 13:41:55.247027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2dd455acfd4'
down_revision: Union[str, Sequence[str], None] = 'c9fd7c7de7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('quality', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_quality'), 'events', ['quality'], unique=False)
    op.drop_column('events', 'latitude')
    op.drop_column('events', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_events_quality'), table_name='events')
    op.drop_column('events', 'quality')
    # ### end Alembic commands ###
